sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rafaelito91/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafaelito91/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'docker-react2'
  env: 'DockerReact2-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-849709122985'
  bucket_path: 'docker-react2'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
